export { default as Home } from './Home/Home'
export { default as Shop } from './Shop/Shop'
export { default as Footer } from './Footer/Footer'
export { default as ProductDetail } from './ProductDetails/ProductDetail'
export { default as Bag } from './Cart/Bag'
export { default as Checkout } from './Checkout/Checkout'
export { default as Error } from './Error'
export { default as Apple } from './Shop/Apple'
export { default as Samsung } from './Shop/Samsung'
export { default as Nav} from './Nav/Nav'
export { default as Smartphones} from './Shop/Smartphones'
export { default as Scrollbutton} from './others/Scrollbutton'